"""
Django settings for example_project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

Powered by Django Split Settings - https://pypi.org/project/django-split-settings/
"""

from split_settings.tools import include
from split_settings.tools import optional


include(
    "base.py",
    "applications.py",
    "celery.py",
    "database.py",
    "emails.py",
    "logging.py",
    "middlewares.py",
    "security.py",
    "sentry.py",
    "twilio.py",
    "versioning.py",
)
